// This file is generated by Deepseek-V3, an AI assistant specialized in Convex and TypeScript.

import { ObjectType, v, ConvexError } from 'convex/values';
import { defineTable, paginationOptsValidator } from "convex/server";
import { mutation, query } from '../_generated/server';
import { Doc, Id } from "../_generated/dataModel";

export const table = 'characterCodex';
export const idCharacterCodex = v.id(table);

export const characterCodexSerialized = {
  character_name: v.string(),
  description: v.string(),
  genre: v.string(),
  media_source: v.string(),
  media_type: v.string(),
  scenario: v.string()
};

export type CharacterCodexTable = typeof table;
export type CharacterCodexId = Id<CharacterCodexTable>;
export type CharacterCodexDoc = Doc<CharacterCodexTable>;

export type SerializedCharacterCodex = ObjectType<typeof characterCodexSerialized>;

export const tableSchema = defineTable(characterCodexSerialized);

export const read = query({
  args: { id: idCharacterCodex },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});

export const list = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db.query(table).collect();
  },
});

export const page = query({
  args: { opts: paginationOptsValidator },
  handler: async (ctx, args) => {
    return await ctx.db.query(table).paginate(args.opts);
  },
});
