// This file is generated by Deepseek-V3, an AI assistant specialized in Convex and TypeScript.

import { ObjectType, v, ConvexError } from 'convex/values';
import { defineTable, paginationOptsValidator } from "convex/server";
import { mutation, query } from '../_generated/server';
import { Doc, Id } from "../_generated/dataModel";

export const table = 'events'; // 表名改为 events
export const indexName_ByWorldId = 'by_worldId';
export const idEvent = v.id(table);

export const eventSerialized = {
  eventName: v.string(),
  description: v.optional(v.string()),
  triggerMode: v.union(v.literal('time'), v.literal('space'), v.literal('command')),
  worldId: v.string(),
  modifyTime: v.number(),
};

const { modifyTime, ...insertArgs } = eventSerialized;
const { ..._updateArgs } = insertArgs;
const updateArgs = { id: idEvent, ..._updateArgs };
const deleteArgs = { id: idEvent };

export type EventTable = typeof table;
export type EventId = Id<EventTable>;
export type EventDoc = Doc<EventTable>;

export type SerializedEvent = ObjectType<typeof eventSerialized>;
export type InsertArgs = ObjectType<typeof insertArgs>;
export type UpdateArgs = ObjectType<typeof updateArgs>;
export type DeleteArgs = ObjectType<typeof deleteArgs>;

export const tableSchema = defineTable(eventSerialized)
  .index(indexName_ByWorldId, ["worldId"]);

export const create = mutation({
  args: insertArgs,
  handler: async (ctx, args) => {
    const modifyTime = +new Date();
    return await ctx.db.insert(table, { ...args, modifyTime });
  },
});

export const read = query({
  args: { id: idEvent },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.id);
  },
});

export const list = query({
  args: { worldId: v.string() },
  handler: async (ctx, args) => {
    const { worldId } = args;
    return await ctx.db.query(table).withIndex(indexName_ByWorldId, (q) =>
      q
        .eq("worldId", worldId)
    ).collect();
  },
});

export const page = query({
  args: { worldId: v.string(), opts: paginationOptsValidator },
  handler: async (ctx, args) => {
    const { worldId, opts } = args;
    return await ctx.db.query(table).withIndex(indexName_ByWorldId, (q) =>
      q
        .eq("worldId", worldId)
    ).paginate(opts);
  },
});

export const update = mutation({
  args: updateArgs,
  handler: async (ctx, args) => {
    const { id, ...patchData } = args;
    const modifyTime = +new Date();
    await ctx.db.patch(id, { ...patchData, modifyTime });
  },
});

export const delete_ = mutation({
  args: deleteArgs,
  handler: async (ctx, args) => {
    const { id } = args;
    await ctx.db.delete(id);
  },
});